spring:
  application:
    name:user-service
server:
  port:9001
eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:8082/eureka/
    register-with-eureka:true
    registryFetchIntervalSeconds:20
spring:
  main:
    allow-bean-definition-overriding:true
